# Whether the all channel should be shown. This channel will combine all tabs into one channel. Defaults to true. 
# Messages sent while viewing this will be sent to the last selected channel.
enable-all: true
# Which channel system messages should be sent to. Set to all to send to all channels. Defaults to all.
system-messages: all
# List of channels and their configuration
channels:
  # Internal channel name. Used for the switching commands, though players shouldn't normally see these. 
  # If channel is private, also forms the permission name in the form of dotchat.channel.<channel>
    # name: The in-game display name of the channel. Defaults to the internal channel name.
    # public: Whether the channel is public or requires permission to join. Defaults to true.
    # auto-join: Whether players join the channel by default. Defaults to true.
    # can-leave: Whether players can leave this channel. Defaults to true.
    # can-talk: Whether players can leave this send messages to the channel. Defaults to true.
    #           This should generally be true unless you have a dedicated system messages channel.
    # history: Whether players are sent the chat history after joining the channel. Defaults to true.
  global:
    name: Global
    public: true
    auto-join: true
    can-leave: false
    can-talk: true
    history: true
  staff:
    name: Staff
    public: false
    auto-join: true
    can-leave: false
    can-talk: true
    history: true
  trade:
    name: Trade
    public: true
    auto-join: true
    can-leave: true
    can-talk: true
    history: false
    